### ISSUE TITLE
not found.

### ISSUE THREAD

**Issue by Bronxphoneix** [cdangerdouglas/keyword_finder_web_crawler#2]
website_to_crawl = 'hashtoolkit.com' 		#website.com  -do not include 'www.'' or 'http'
keyword_to_search_for = 'Recently' #keyword or phrase

but not found,

so it word place homepage

**Comment by BAG-OF-CHIPS-XX** [comment]
The website might be using javascript/ of Iframes to render content. If that is the case then this crawler will not pick up the content. ONLY regular html/ css rendered content will be found by this crawler.

**Comment by BAG-OF-CHIPS-XX** [comment]
I just tried your query and it is working. there was a tab/space issue. Reinstall the repo and try again.
